# Generated by Django 4.2.7 on 2023-11-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('expired_date', models.DateField(blank=True, default=None, null=True)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
