version: "3.9"
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./backend_test/:/app/backend_test
    env_file: ./docker/local.env
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
    links:
      - db:test_db
  db:
    image: postgres:12.0-alpine
    restart: always
    ports:
      - "5436:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=user"
      - "POSTGRES_DB=test_db"
